.TH "src Directory Reference" 3 "Wed Mar 11 2015" "Version 1.0" "Lab1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBbenchmark_frm\&.cpp\fP"
.br
.ti -1c
.RI "file \fBbenchmark_frm\&.h\fP"
.br
.ti -1c
.RI "file \fBinputfile_txt\&.cpp\fP"
.br
.ti -1c
.RI "file \fBinputfile_txt\&.h\fP"
.br
.RI "\fIA new input files class\&. \fP"
.ti -1c
.RI "file \fBmain\&.cpp\fP"
.br
.in -1c
