.TH "src/inputfile_txt.h" 3 "Wed Mar 11 2015" "Version 1.0" "Lab1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/inputfile_txt.h \- A new input files class\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <string>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <cstdio>\fP
.br
\fC#include <cassert>\fP
.br
\fC#include <ctime>\fP
.br
\fC#include <random>\fP
.br
\fC#include <boost/algorithm/string/erase\&.hpp>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBInputFiles\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const int \fBFIRST_ARGUMENT\fP = 1"
.br
.RI "\fIFirst argument from command prompt (name of the program) \fP"
.ti -1c
.RI "const int \fBUNDEF_VALUE\fP = 1"
.br
.ti -1c
.RI "const int \fBPROGRAM_NAME\fP = 1"
.br
.in -1c
.SH "Detailed Description"
.PP 
A new input files class\&. 


.PP
Definition in file \fBinputfile_txt\&.h\fP\&.
.SH "Variable Documentation"
.PP 
.SS "const int FIRST_ARGUMENT = 1"

.PP
First argument from command prompt (name of the program) 
.SS "const int PROGRAM_NAME = 1"

.SS "const int UNDEF_VALUE = 1"

.SH "Author"
.PP 
Generated automatically by Doxygen for Lab1 from the source code\&.
