.TH "src/inputfile_txt.cpp" 3 "Thu Mar 12 2015" "Version 1.1" "Lab 1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/inputfile_txt.cpp \- Source code for InputFile class\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'inputfile_txt\&.h'\fP
.br

.SH "Detailed Description"
.PP 
Source code for InputFile class\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for Lab 1 from the source code\&.
