.TH "src/main.cpp" 3 "Thu Mar 12 2015" "Version 1.1" "Lab 1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/main.cpp \- Master file\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'inputfile_txt\&.h'\fP
.br
\fC#include 'benchmark_frm\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Detailed Description"
.PP 
Master file\&. 


.SH "Function Documentation"
.PP 
.SS "int main (int argc, char * argv[])"
Container for sizes from command prompt
.PP
First argument is a name of the program so i = 1 
.PP
.nf
9 {
10     //! Container for sizes from command prompt
11     std::vector<int>FilesSizes;
12 
13     //! First argument is a name of the program so i = 1
14     for (int i = 1; i < argc ; i++)
15         FilesSizes\&.push_back(atoi(argv[i]));
16     
17     InputFiles newFilesList(argc, FilesSizes);
18     Benchmark NewTest;
19     newFilesList\&.generate_random_int_data();
20     NewTest\&.test(newFilesList);
21 }
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for Lab 1 from the source code\&.
