.TH "C:/Users/Daniel/Desktop/myStuff/209185/Lab2/src Directory Reference" 3 "Thu Mar 19 2015" "Version 1.0" "Lab 2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Daniel/Desktop/myStuff/209185/Lab2/src Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBbenchmark_frm\&.cpp\fP"
.br
.RI "\fISource code for \fBBenchmark\fP class\&. \fP"
.ti -1c
.RI "file \fBbenchmark_frm\&.h\fP"
.br
.RI "\fIA \fBBenchmark\fP class\&. \fP"
.ti -1c
.RI "file \fBinputfile_txt\&.cpp\fP"
.br
.RI "\fISource code for InputFile class\&. \fP"
.ti -1c
.RI "file \fBinputfile_txt\&.h\fP"
.br
.RI "\fIA InputFile class\&. \fP"
.ti -1c
.RI "file \fBlist\&.cpp\fP"
.br
.RI "\fIA source code for list data structure\&. \fP"
.ti -1c
.RI "file \fBlist\&.h\fP"
.br
.RI "\fIOwn implementation of linked list\&. \fP"
.ti -1c
.RI "file \fBlist_node\&.cpp\fP"
.br
.RI "\fIA source code for \fBLNode\fP class\&. \fP"
.ti -1c
.RI "file \fBlist_node\&.h\fP"
.br
.RI "\fINodes for list\&. \fP"
.ti -1c
.RI "file \fBmain\&.cpp\fP"
.br
.RI "\fIA master file\&. \fP"
.ti -1c
.RI "file \fBqueue\&.cpp\fP"
.br
.ti -1c
.RI "file \fBqueue\&.h\fP"
.br
.RI "\fIOwn implementation of queue\&. \fP"
.ti -1c
.RI "file \fBstack\&.cpp\fP"
.br
.RI "\fIA stack class source code\&. \fP"
.ti -1c
.RI "file \fBstack\&.h\fP"
.br
.RI "\fIOwn implementation of stack data structure\&. \fP"
.ti -1c
.RI "file \fBtree\&.cpp\fP"
.br
.RI "\fIA source file for \fBTree\fP class\&. \fP"
.ti -1c
.RI "file \fBtree\&.h\fP"
.br
.RI "\fIOwn implementation of tree data structure\&. \fP"
.ti -1c
.RI "file \fBtree_node\&.cpp\fP"
.br
.RI "\fIA source file for \fBNode\fP class\&. \fP"
.ti -1c
.RI "file \fBtree_node\&.h\fP"
.br
.RI "\fIOwn implementation of tree data structure (nodes of tree) \fP"
.in -1c
