.TH "C:/Users/Daniel/Desktop/myStuff/209185/Lab2/src/list_node.h" 3 "Thu Mar 19 2015" "Version 1.0" "Lab 2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Daniel/Desktop/myStuff/209185/Lab2/src/list_node.h \- Nodes for list\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBLNode\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBLIST_NODE_H\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Nodes for list\&. 


.PP
Definition in file \fBlist_node\&.h\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define LIST_NODE_H"

.SH "Author"
.PP 
Generated automatically by Doxygen for Lab 2 from the source code\&.
