.TH "C:/Users/Daniel/Desktop/myStuff/209185/Lab2/src/list.h" 3 "Thu Mar 19 2015" "Version 1.0" "Lab 2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Daniel/Desktop/myStuff/209185/Lab2/src/list.h \- Own implementation of linked list\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'benchmark_frm\&.h'\fP
.br
\fC#include 'inputfile_txt\&.h'\fP
.br
\fC#include 'list_node\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBList\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Own implementation of linked list\&. 


.PP
Definition in file \fBlist\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Lab 2 from the source code\&.
