.TH "C:/Users/Daniel/Desktop/myStuff/209185/Lab2/src/main.cpp" 3 "Thu Mar 19 2015" "Version 1.0" "Lab 2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Daniel/Desktop/myStuff/209185/Lab2/src/main.cpp \- A master file\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'tree\&.h'\fP
.br
\fC#include 'tree_node\&.h'\fP
.br
\fC#include 'queue\&.h'\fP
.br
\fC#include 'list\&.h'\fP
.br
\fC#include 'stack\&.h'\fP
.br
\fC#include 'inputfile_txt\&.h'\fP
.br
\fC#include 'benchmark_frm\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Detailed Description"
.PP 
A master file\&. 


.PP
Definition in file \fBmain\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char * argv[])"

.PP
.nf
15                                 {
16     
17     // contains only one size, implementation from Lab1
18     std::vector<int>fileSize;
19     // First argument is a name of the program so i = 1
20     for (int i = 1; i < argc; i++)
21         fileSize\&.push_back(atoi(argv[i]));
22     
23     InputFiles openFile(argc, fileSize);
24     openFile\&.generate_random_int_data();
25 
26     Benchmark treeTest;
27     Tree newTree(openFile,treeTest);
28 
29     Benchmark queueTest(treeTest);
30     Queue newQueue(openFile, queueTest);
31 
32     Benchmark listTest(treeTest);
33     List newList(openFile, listTest);
34 
35     Benchmark stackTest(treeTest);
36     Stack newStack(openFile, stackTest);
37 
38     std::cin\&.clear();
39     std::cin\&.get();
40     return 0;
41 }
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for Lab 2 from the source code\&.
