.TH "C:/Users/Daniel/Desktop/myStuff/209185/Lab2/src/stack.cpp" 3 "Thu Mar 19 2015" "Version 1.0" "Lab 2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Daniel/Desktop/myStuff/209185/Lab2/src/stack.cpp \- A stack class source code\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'stack\&.h'\fP
.br

.SH "Detailed Description"
.PP 
A stack class source code\&. 


.PP
Definition in file \fBstack\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Lab 2 from the source code\&.
