.TH "todo" 3 "Thu Mar 12 2015" "Version 1.1" "Lab 1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
todo \- Todo List 

.IP "\fBMember \fBBenchmark::generateRaport\fP (long double nextTime, int size)\fP" 1c
FILE OVERWRITING, NEED TO IMPLEMENT NEW NAMES  
.IP "\fBMember \fBInputFiles::InputFiles\fP ()\fP" 1c
EXCEPTIONS HANDLING 
.PP

