.TH "C:/Users/Daniel/Desktop/myStuff/209185/Lab2/src/tree.cpp" 3 "Thu Mar 19 2015" "Version 1.0" "Lab 2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Daniel/Desktop/myStuff/209185/Lab2/src/tree.cpp \- A source file for \fBTree\fP class\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'tree\&.h'\fP
.br

.SH "Detailed Description"
.PP 
A source file for \fBTree\fP class\&. 


.PP
Definition in file \fBtree\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Lab 2 from the source code\&.
