.TH "C:/Users/Daniel/Desktop/myStuff/209185/Lab2/src/tree.h" 3 "Thu Mar 19 2015" "Version 1.0" "Lab 2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Daniel/Desktop/myStuff/209185/Lab2/src/tree.h \- Own implementation of tree data structure\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'tree_node\&.h'\fP
.br
\fC#include 'inputfile_txt\&.h'\fP
.br
\fC#include 'benchmark_frm\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTree\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const int \fBFIRST_FILE\fP = 0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Own implementation of tree data structure\&. 


.PP
Definition in file \fBtree\&.h\fP\&.
.SH "Variable Documentation"
.PP 
.SS "FIRST_FILE = 0"
const int for first file index 
.SH "Author"
.PP 
Generated automatically by Doxygen for Lab 2 from the source code\&.
